version: '3.3'

services:
  app:
    env_file: './services/app/.env'
    container_name: simpleweather
    build:
      context: services/app
      dockerfile: Dockerfile.development
    expose:
      - '3000'

  nginx:
    container_name: simpleweather_nginx
    build:
      context: services/nginx
    ports:
      - '80:80'
    depends_on:
      - app